Implement modelling-for-generating-alternatives using mathematical programming
TulipaEnergy/MGA.jl pull request #5
Opened 2024-05-08 09:54 UTC by marnoldus

# Pull request details

## Describe the changes made in this pull request
Imlements the modelling-for-generating-alternatives problem using mathematical programming. One or more alternatives can be found by iteratively repeating the process.

## List of related issues or pull requests
Closes #1

2024-05-13 07:45 UTC, greg-neustroev commented on Project.toml
> +SCIP = "82193955-e24f-5292-bf16-6f2c5261a85f"
Can you avoid adding specific solvers as dependencies, e.g., so that people who want to use Gurobi do not need to install SCIP.

2024-05-13 07:46 UTC, greg-neustroev commented on src/MGA.jl
>  module MGA
Should this be NearOptimalAlternatives as per the group chat discussion?

2024-05-13 07:47 UTC, greg-neustroev commented on src/alternative-optimisation.jl
> +Transform a JuMP model into a model solving its corresponding modelling-for-generating-alternatives problem.
Please explain the functions arguments in the docstring

2024-05-13 07:50 UTC, greg-neustroev commented on src/alternative-optimisation.jl
> +  end
```Julia
variables = all_variables(model)
solution = value.(variables)
```

this should work, I think

2024-05-13 07:57 UTC, greg-neustroev commented on src/alternative-optimisation.jl
> +    c = @constraint(model, original_objective, old_objective ≥ optimal_value * (1 - optimality_gap))
`c =` should be omitted

2024-05-13 07:58 UTC, greg-neustroev commented on src/alternative-optimisation.jl
> +  variables = VariableRef[]
this part appeared earlier in the code. can it be put into a function?

2024-05-13 07:59 UTC, greg-neustroev commented on src/alternative-optimisation.jl
> +  variables = VariableRef[]
lines 61-67 I mean

2024-05-13 08:02 UTC, greg-neustroev commented on src/generate-alternatives.jl
> +  create_alternative_problem!(model, optimality_gap, metric, selected_variables)
can we do a more descriptive name than `alternative_model`?

2024-05-13 08:03 UTC, greg-neustroev commented on src/generate-alternatives.jl
> +  create_alternative_problem!(model, optimality_gap, metric, selected_variables)
maybe even `alternative_generating_model`?

2024-05-13 08:05 UTC, greg-neustroev requested changes
Nice job, but I do have some comments on the code. I think you should improve the documentation before submitting. Also, some of the CI tests did not pass (it relates to using SCIP). In TulipaEnegryModel.jl tests we use HiGHs, I think, maybe should do the same here for consistency?

2024-05-13 08:32 UTC, marnoldus commented on Project.toml
> +SCIP = "82193955-e24f-5292-bf16-6f2c5261a85f"
This is not actually used, I forgot to remove it

2024-05-13 08:33 UTC, marnoldus commented on src/MGA.jl
>  module MGA
I will update this in a future PR because it requires some other changes in the repo

2024-05-13 08:34 UTC, marnoldus commented on src/alternative-optimisation.jl
> +  @objective(model, Max, old_objective + Distances.evaluate(metric, variables, solution))
old_objective here is the cumulative sum of distances between previously found solutions. So, we do not need this parameter but a more descriptive name for `old_objective`.

2024-05-13 08:39 UTC, marnoldus commented
> Nice job, but I do have some comments on the code. I think you should improve the documentation before submitting. Also, some of the CI tests did not pass (it relates to using SCIP). In TulipaEnegryModel.jl tests we use HiGHs, I think, maybe should do the same here for consistency?

For some reason I thought HiGHS was not able to deal with the alternative generation problem due to the quadratic constraints, but apparently it is, so I'll change it.

2024-05-13 08:50 UTC, greg-neustroev commented on src/alternative-optimisation.jl
> +  @objective(model, Max, old_objective + Distances.evaluate(metric, variables, solution))
`cumulative_distance`?

2024-05-13 08:50 UTC, marnoldus commented
> > Nice job, but I do have some comments on the code. I think you should improve the documentation before submitting. Also, some of the CI tests did not pass (it relates to using SCIP). In TulipaEnegryModel.jl tests we use HiGHs, I think, maybe should do the same here for consistency?
> 
> For some reason I thought HiGHS was not able to deal with the alternative generation problem due to the quadratic constraints, but apparently it is, so I'll change it.

After some more looking into it, HiGHS is not able to deal with non-convex QP's. We will change to Ipopt.

2024-05-13 09:35 UTC, marnoldus commented on src/alternative-optimisation.jl
> +  variables = VariableRef[]
With the proposed changes in the other comment, two lines are left so I think a function for that is a bit too much

2024-05-14 09:26 UTC, greg-neustroev approved these changes
Looking good

2024-05-14 09:48 UTC, merged